services:
  - type: web
    name: text-intent-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: ENV
        value: production
